name: Testing API
on: [push, pull_request]
jobs: 
  testing-api:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkot the repo
        uses: actions/checkout@v2
      - name: Creating and activating virtualenv
        run: |
          pip install --upgrade virtualenv
          virtualenv -p python3 venv
          source venv/bin/activate
      - name: Installing dependencies
        run: |
             pip install dvc[gs]
             pip install -r requirements_test.txt
      - name: Test API
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull models/model.pkl.dvc -r model-track
          pytest test.py